# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
      
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: ivan1404/kiii_project
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        

  helm-lint:
    name: Helm lint and release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: deploy to cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
             KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
             args: kubectl apply -f manifest.yaml
      - name: Helm install
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --install github-kiii_project ./helm-chart
          kubeconfig: '${{ secrets.KUBECONFIG }}'        
        
      
